### ISSUE TITLE
Finder Methods aren't Working - JRuby 1.6.2

### ISSUE THREAD

**Issue by efleming** [appoxy/simple_record#38]
None of the finder methods are working with JRuby.  They all return the same error:

ArgumentError: wrong number of arguments (2 for 1) from ...simple_record-2.1.8/lib/simple_record/active_sdb.rb:441:in `select_all_by_'

**Comment by jmclachlan** [comment]
It seems like simple_record does not work at all with JRuby. I am getting an this error:
Aws::AwsError: sdb.amazonaws.com temporarily unavailable: (undefined method `read_nonblock' for #<OpenSSL::SSL::SSLSocket:0x174c2fa5>)
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/http_connection-1.4.1/lib/right_http_connection.rb:332:in`request'
    from org/jruby/RubyKernel.java:1419:in `loop'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/http_connection-1.4.1/lib/right_http_connection.rb:322:in`request'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/aws-2.5.6/lib/awsbase/awsbase.rb:557:in `request_info_impl'
    from /Users/jmclachlan/.rvm/rubies/jruby-1.6.3/lib/ruby/1.9/benchmark.rb:294:in`measure'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/aws-2.5.6/lib/awsbase/benchmark_fix.rb:30:in `add!'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/aws-2.5.6/lib/awsbase/awsbase.rb:557:in`request_info_impl'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/aws-2.5.6/lib/awsbase/awsbase.rb:316:in `request_info2'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/aws-2.5.6/lib/sdb/sdb_interface.rb:106:in`request_info'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/aws-2.5.6/lib/sdb/sdb_interface.rb:296:in `create_domain'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/simple_record-2.2.0/lib/simple_record/active_sdb.rb:246:in`create_domain'
    from (irb):1:in `evaluate'
    from org/jruby/RubyKernel.java:1093:in`eval'
    from org/jruby/RubyKernel.java:1419:in `loop'
    from org/jruby/RubyKernel.java:1205:in`catch'
    from org/jruby/RubyKernel.java:1205:in `catch'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/railties-3.0.9/lib/rails/commands/console.rb:44:in`start'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/railties-3.0.9/lib/rails/commands/console.rb:8:in `start'
    from /Users/jmclachlan/.rvm/gems/jruby-1.6.3/gems/railties-3.0.9/lib/rails/commands.rb:23:in`(root)'
    from org/jruby/RubyKernel.java:1047:in `require'
