### ISSUE TITLE
Not accessable from local machine but it works from my amazon server 

### ISSUE THREAD

**Issue by blazetango** [appoxy/simple_record#55]
Initally I was able to work on my local machine and access simple db record easliy  but from last few months i m faceing lot of issues .
when i try to access SimpleDb Records  i get this 
 Retailer.all
Aws::AwsError: sdb.ap-southeast-2.amazonaws.com temporarily unavailable: (execution expired)
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/http_connection-1.4.4/lib/right_http_connection.rb:335:in `request'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/http_connection-1.4.4/lib/right_http_connection.rb:325:in`loop'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/http_connection-1.4.4/lib/right_http_connection.rb:325:in `request'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/aws-2.9.1/lib/awsbase/awsbase.rb:560:in`request_info_impl'
    from /home/chetan/.rvm/rubies/ruby-1.8.7-p371/lib/ruby/1.8/benchmark.rb:293:in `measure'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/aws-2.9.1/lib/awsbase/benchmark_fix.rb:30:in`add!'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/aws-2.9.1/lib/awsbase/awsbase.rb:560:in `request_info_impl'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/aws-2.9.1/lib/awsbase/awsbase.rb:319:in`request_info2'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/aws-2.9.1/lib/sdb/sdb_interface.rb:106:in `request_info'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/aws-2.9.1/lib/sdb/sdb_interface.rb:704:in`select'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/simple_record-2.1.0/lib/simple_record/active_sdb.rb:411:in `sql_select'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/simple_record-2.1.0/lib/simple_record/active_sdb.rb:293:in`find_with_metadata'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/simple_record-2.1.0/lib/simple_record.rb:963:in `find'
    from /home/chetan/.rvm/gems/ruby-1.8.7-p371/gems/simple_record-2.1.0/lib/simple_record.rb:1002:in`all'
    from (irb):2

The same code is working on amazon Ec2  medium instance (amazon LInux ) 
ruby 1.8.7
rails 3.2.11
and simple_record 2.1.0
Please can you help me out

**Comment by treeder** [comment]
Maybe something to do with AWS security groups?

**Comment by blazetango** [comment]
I am trying to workout some solution to this problem ...
My local development is at a hault . Just to confirm this issue i install extension on chrome and was able to access some record on browser but the gem is not constantly giveing and error 
Aws::AwsError: sdb.ap-southeast-2.amazonaws.com temporarily unavailable: (execution expired)
ruby 1.8.7
rails 3.2.11
and simple_record 2.1.0
Please  help me out
